import Head from 'next/head'
import React, { useState } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'
import Nav from '../components/nav'
import Wave from '../components/wave'
import Footer from '../components/footer'
import Contact from '../components/contact'
import { FormspreeProvider } from '@formspree/react'
import Link from 'next/link'

export default function Home() {



  const technologies = ['HTML5', 'CSS3', 'TailwindCSS', 'NextJS', 'JavaScript', 'Java', 'ReactJS', 'MongoDB', 'SQL', 'C#'];


  return (
    <div className='scroll-smooth'>
      <Head>
        <title>Michael C \ Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <section id="home" className='min-h-fit bg-[#9867C5] py-40'>
        <div className="container m-auto max-w-7xl flex justify-center h-[50vh] items-center flex-col">
          <div className='md:flex-row flex'>
            <p className='flex md:text-3xl md:!leading-[5rem] m-0 text-xl leading-10 text-white'>Hey, my name is</p>
            <h1 className='text-white pl-2 md:text-6xl text-3xl'>Michael Connor</h1>
          </div>
          <p className='m-0 text-white md:text-3xl text-xl text-center '>
            I am a software engineering student and aspiring web developer
          </p>
          <button className="bg-[#0e283c] hover:bg-[#20639B] z-50 transition-colors duration-300 text-white font-bold py-2 px-4 rounded inline-flex mt-4 items-center">
            {/* <svg className="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" /></svg> */}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-discord mr-2" viewBox="0 0 16 16">
            <path d="M13.545 2.907a13.227 13.227 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.19 12.19 0 0 0-3.658 0 8.258 8.258 0 0 0-.412-.833.051.051 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.041.041 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032c.001.014.01.028.021.037a13.276 13.276 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019c.308-.42.582-.863.818-1.329a.05.05 0 0 0-.01-.059.051.051 0 0 0-.018-.011 8.875 8.875 0 0 1-1.248-.595.05.05 0 0 1-.02-.066.051.051 0 0 1 .015-.019c.084-.063.168-.129.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.052.052 0 0 1 .053.007c.08.066.164.132.248.195a.051.051 0 0 1-.004.085 8.254 8.254 0 0 1-1.249.594.05.05 0 0 0-.03.03.052.052 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.235 13.235 0 0 0 4.001-2.02.049.049 0 0 0 .021-.037c.334-3.451-.559-6.449-2.366-9.106a.034.034 0 0 0-.02-.019Zm-8.198 7.307c-.789 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.45.73 1.438 1.613 0 .888-.637 1.612-1.438 1.612Zm5.316 0c-.788 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.451.73 1.438 1.613 0 .888-.631 1.612-1.438 1.612Z"/>
            </svg>
           <Link href="discord.gg/leagueglobal">
                <a>Join Here</a> 
            </Link>
          </button>
          {/* <button className="bg-[#BE93D4] hover:bg-purple-600 transition-colors duration-300 text-white font-bold py-2 px-4 rounded inline-flex mt-4 items-center">
            <svg className="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" /></svg>
            <span>Download CV</span>
          </button> */}
        </div>
      </section>
      <Wave fill={"BE93D4"} bg={"9867C5"} />
      <section id="about" className='min-h-fit section-padding bg-[#BE93D4]'>
        <div className='container'>
          <h1 className='text-5xl text-white p-4'>About Me</h1>
          <p className='text-white p-2'>Hello, I&apos;m Michael Connor. I&apos;m a full time university student studying Software Engineering and also study web development on the side. I have a strong passion for both software and website development, and currently have experience creating both software and websites using JavaScript / NextJs / Reactjs / Java and some other frameworks</p>
          <h1 className='text-white p-2 text-5xl'>Technologies I&apos;ve worked with:</h1>
          <ul className='flex flex-wrap gap-4 my-3 p-2 text-white'>
            {
              technologies.map((t, i) => (
                <li key={i}>{t}</li>
              ))
            }
          </ul>
        </div>
        {/* <div className='m-auto max-w-7xl gap-5 grid sm:grid-cols-12 grid-cols-1 container sm:grid-rows-none grid-rows-1'>
          <p className='sm:col-span-6 col-span-12'>
            Image
          </p>
          <p className='sm:col-span-6 col-span-12'>
            dummy text
          </p>
        </div> */}
      </section>
      <Wave fill={"9867C5"} bg={"BE93D4"} />
      <section id="projects" className='h-fit bg-[#9867C5] py-20'>

        <Card />

        {/* <button onClick={showMoreItems} className="bg-[#BE93D4] hover:bg-purple-600 transition-colors duration-300 text-white font-bold py-2 px-4 w-[7.1rem] text-center
          mx-auto rounded inline-flex mt-4 items-center"> Load More</button> */}

      </section>
      <Wave fill={"BE93D4"} bg={"9867C5"} />
      <section id="contact" className='h-[80vh] bg-[#BE93D4] py-20'>
        <FormspreeProvider project="1914443541589786412">
          <Contact />
        </FormspreeProvider>

      </section>
      <Footer />
    </div>
  )
}
